### PR TITLE
Range enemy and fixes

### PR DESCRIPTION
**Pull request by Galaxy25**
Features added:
Laptop goon
Death when loss of health
Tilemap test

### CODE REVIEW

**Review by BrandonPacewic — CHANGES_REQUESTED** [review]
There is currently a merge conflict with `Assets/Prefabs/Player.prefab`

**Comment by Galaxy25** [comment]
Merged it successfully with the main branch. My bad for not putting Closes #40

**Comment by BrandonPacewic** [comment]
Am I correct in saying that this also closes #55?

**Comment by Galaxy25** [comment]
Forgot it closes #55

**Review by BrandonPacewic — APPROVED** [review]
I'm getting ready to merge and updating the change log - please @me if any other changes are pushed.

**Pull request merged**
