### PR TITLE
Added New Map Assets

### LINKED ISSUE #153: Update the map with the new icons
The current level map is using filler icons. We will replace these with the ones we made in house.

### LINKED ISSUE #160: Map Icons with are Assets

### PR DESCRIPTION
**Pull request by BrandonPacewic**
Closes #160.
Closes #153.

TODO:
- [x] Boss icon
- [x] Corruption room

### CODE REVIEW

**Comment by Galaxy25** [comment]
@BrandonPacewic Everything is in the drive

**Comment by BrandonPacewic** [comment]
@Galaxy25 Will the corruption remover icon go to a specific scene or just manipulate the corruption level?

**Comment by Galaxy25** [comment]
@BrandonPacewic Specific scene

**Comment by Galaxy25** [comment]
@BrandonPacewic The first time I click a object its works. The second time the maps disappears.

DOTBEWEEN is telling me this "<color=#ff7337><color=#0099bc><b>DOTWEEN ► </b></color> SAFE MODE ►</color> DOTween's safe mode captured 3 errors. This is usually ok (it's what safe mode is there for) but if your game is encountering issues you should set Log Behaviour to Default in DOTween Utility Panel in order to get detailed warnings when an error is captured (consider that these errors are always on the user side).
- 3 missing target or field errors
UnityEngine.Debug:LogWarning (object)
DG.Tweening.Core.Debugger:LogSafeModeReport (object) (at D:/DG/_Develop/__UNITY3_CLASSES/_Holoville/__DOTween/_DOTween.Assembly/DOTween/Core/Debugger.cs:80)
DG.Tweening.Core.DOTweenComponent:OnDestroy () (at D:/DG/_Develop/__UNITY3_CLASSES/_Holoville/__DOTween/_DOTween.Assembly/DOTween/Core/DOTweenComponent.cs:156)

"

**Comment by BrandonPacewic** [comment]
> @BrandonPacewic The first time I click a object its works. The second time the maps disappears.
> 
> DOTBEWEEN is telling me this "<color=#ff7337><color=#0099bc>DOTWEEN ► SAFE MODE ► DOTween's safe mode captured 3 errors. This is usually ok (it's what safe mode is there for) but if your game is encountering issues you should set Log Behaviour to Default in DOTween Utility Panel in order to get detailed warnings when an error is captured (consider that these errors are always on the user side).
> 
> * 3 missing target or field errors
>   UnityEngine.Debug:LogWarning (object)
>   DG.Tweening.Core.Debugger:LogSafeModeReport (object) (at D:/DG/_Develop/__UNITY3_CLASSES/_Holoville/__DOTween/_DOTween.Assembly/DOTween/Core/Debugger.cs:80)
>   DG.Tweening.Core.DOTweenComponent:OnDestroy () (at D:/DG/_Develop/__UNITY3_CLASSES/_Holoville/__DOTween/_DOTween.Assembly/DOTween/Core/DOTweenComponent.cs:156)
> 
> "

The dotween thing is different from the problem. I mentioned this earlier but when switching between branches sometimes there is a problem with the way the map is stored. I can so you the solution to this problem at todays meeting.

**Review by Galaxy25 — APPROVED** [review]
The reason why I thought their was a bug will stay in conversation.

**Pull request merged**
