### PR TITLE
Boss

### LINKED ISSUE #149: Boss Fight Bullet Spawn Patterns

### PR DESCRIPTION
**Pull request by Galaxy25**
Closes #149

### CODE REVIEW

**Comment by BrandonPacewic** [comment]
@Galaxy25 Is the scene supposed to change after you kill the boss?

**Comment by Galaxy25** [comment]
@BrandonPacewic I can make a door to bring them to a new scene, but that's for room enhancement

**Comment by Galaxy25** [comment]
Its ready to be merged

**Comment by BrandonPacewic** [comment]
@Galaxy25 One last question, can the boss be damaged while dialogue is going on?

**Comment by Galaxy25** [comment]
@BrandonPacewic Once the pause menu is merged I'll use it to pause the game

**Comment by BrandonPacewic** [comment]
I'm getting ready to merge and updating the change log - please @me if any other changes are pushed.

**Review by BrandonPacewic — APPROVED** [review]

**Pull request merged**
