### PR TITLE
Weapon inventory ammo fix

### LINKED ISSUE #122: Ammo doesn't update with swapping weapons
When using the inventory system the inventory doesn't update the current ammo causing weapons to have more ammo then there limit. This can be fixed by adding another list to keep track of the current ammo for each weapon

### LINKED ISSUE #126: Add `WeaponName` to weapon asset menu
@Galaxy25 Can I get you to update the asset menu for me? I looked at it but could not figure out how to update an already existing asset file.

### LINKED ISSUE #159: Cannot Compile Due to Weapon Inventory
The use of "AssetDatabase" is causing an error because the script only works with the Unity Editor. It doesn't let you compile the script. Change it out with Resource.Load if you want to load images from the script

https://stackoverflow.com/questions/55479804/unity-the-name-assetdatabase-does-not-exist-in-the-current-context
Assets\Scripts\Player\WeaponInventory.cs(64,33): error CS0103: The name 'AssetDatabase' does not exist in the current context

### PR DESCRIPTION
**Pull request by BrandonPacewic**
- Closes #126.
- Closes #122.

I now see why the sniper was so good 😹 

Edit:
- Closes #159.

### CODE REVIEW

**Comment by Galaxy25** [comment]
@BrandonPacewic Can you decrease the interval before someone can swap there weapon again. Everything else looks fine

**Review by Galaxy25 — DISMISSED** [review]

**Comment by Galaxy25** [comment]
@BrandonPacewic Would this script function with multiples of the same weapon?

**Comment by BrandonPacewic** [comment]
> @BrandonPacewic Would this script function with multiples of the same weapon?

Yes.

**Comment by Galaxy25** [comment]
@BrandonPacewic When swapping between weapons the ammo goes back to the max. Also why does adding a weapon move it to the front of the `List`?

**Comment by Galaxy25** [comment]
@BrandonPacewic It should thats why I'm confused

**Comment by Galaxy25** [comment]
@BrandonPacewic I'm getting an error with the index

**Comment by BrandonPacewic** [comment]
Can you let me know what you are doing to cause the problem? Apparently I am not a very good tester as I can't get anything to happen with it.

**Comment by Galaxy25** [comment]
@BrandonPacewic ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
System.Collections.Generic.List`1[T].get_Item (System.Int32 index) (at <88e4733ac7bc4ae1b496735e6b83bbd3>:0)
WeaponInventory.ChangeWeapon (System.Int32 newWeaponIndex, System.Boolean force) (at Assets/Scripts/Player/WeaponInventory.cs:158)
WeaponInventory.Start () (at Assets/Scripts/Player/WeaponInventory.cs:81)

**Comment by Galaxy25** [comment]
@BrandonPacewic Why do we need a 3rd party list for the inventory?

**Comment by BrandonPacewic** [comment]
> @BrandonPacewic Why do we need a 3rd party list for the inventory?

We don't but it's already there for the map.

**Comment by BrandonPacewic** [comment]
Also closes #159.

**Comment by BrandonPacewic** [comment]
@Galaxy25 Hopefully got everything this time.

**Review by Galaxy25 — APPROVED** [review]
Everything feels great! Also it compiles without breaking

**Comment by BrandonPacewic** [comment]
I'm getting ready to merge and updating the change log - please @me if any other changes are pushed.

**Pull request merged**
