### PR TITLE
Health

### PR DESCRIPTION
**Pull request by Dezerack**
Added health for both the player and test enemy no death screen for player and no kill for enemy yet.

### CODE REVIEW

**Review by BrandonPacewic — CHANGES_REQUESTED** [review]
Something does not look quite right. This looks like the code from the `Gun` branch.

**Comment by BrandonPacewic** [comment]
With the merge of gun this branch has also amassed quite the number of merge conflicts.

**Comment by BrandonPacewic** [comment]
I'm not currently available to review your changes. Going to be slow to look at this one 🐌.

**Review by BrandonPacewic — CHANGES_REQUESTED** [review]
I had to re-name the folders to remove the space in their names:

`Enemy Scripts` -> `EnemyScripts`
`Player Scripts` -> `PlayerScripts`

This space was breaking our `clang-format` workflow. Also generally it's not best to have spaces in folder names 🙃.

Please fix the Unity errors that this folder rename caused 🐈

**Comment by BrandonPacewic** [comment]
Looks like there are still lots of merge conflicts. Please fix these before we continue the review.

**Comment by Galaxy25** [comment]
For now, let's only keep the C# scripts. I can take a look at merging after that. @BrandonPacewic

**Comment by Galaxy25** [comment]
I'm not sure how to remove scripts that are being merged @BrandonPacewic

**Review by BrandonPacewic — DISMISSED** [review]
Incredible work! 🚀

**Comment by Galaxy25** [comment]
@BrandonPacewic I don't see any merge conflicts with these files so does that mean they were completed yesterday?

**Comment by Galaxy25** [comment]
@Dezerack Why does the enemy need an invincibility timer? Wouldn't this cause problems with weapons with multiple bullets

**Comment by BrandonPacewic** [comment]
> @BrandonPacewic I don't see any merge conflicts with these files so does that mean they were completed yesterday?

Yes I fixed all of the merge conflicts.

**Comment by Galaxy25** [comment]
Whoever renamed the variables make sure you rename them throughout the entire script. Everything else is working and we can always turn off the invincibly timer if we don't like it on the enemies.

**Review by Galaxy25 — APPROVED** [review]

**Comment by BrandonPacewic** [comment]
> Whoever renamed the variables make sure you rename them throughout the entire script. Everything else is working and we can always turn off the invincibly timer if we don't like it on the enemies.

My bad, I figured that you would fix it for me 🙃. I'll use find and replace next time to hopefully avoid this in the future.

**Review by BrandonPacewic — APPROVED** [review]
I'm getting ready to merge and updating the change log - please @me if any other changes are pushed.

**Comment by Galaxy25** [comment]
Closes #25

**Pull request merged**
