### PR TITLE
Player Run Stat Saver

### LINKED ISSUE #185: Player saves between runs

### PR DESCRIPTION
**Pull request by BrandonPacewic**
Closes #185.

### CODE REVIEW

**Comment by BrandonPacewic** [comment]
@Galaxy25 This is what I came up with for the initial setup. Let me know if this makes sense and is how you want this system to be set up.

**Comment by Galaxy25** [comment]
@BrandonPacewic This system seems to make sense. Just have a scene to pick what data they want to use and store money, health upgrades, and weapon upgrades.

**Comment by BrandonPacewic** [comment]
@Galaxy25 Seems to work, just need a way to update the initial starting player stats and a shop to change them.

**Review by Galaxy25 — COMMENTED** [review]
@BrandonPacewic The save manager needs to only be called once per opening not once per scene.

**Comment by Galaxy25** [comment]
@BrandonPacewic Also create a example setup for the player stats

**Review by Galaxy25 — APPROVED** [review]

**Review by Galaxy25 — APPROVED** [review]

**Comment by BrandonPacewic** [comment]
I'm getting ready to merge and updating the change log - please @me if any other changes are pushed.

**Pull request merged**
