### PR TITLE
Added mixer to audio

### LINKED ISSUE #131: Add Mixers to Audio

### PR DESCRIPTION
**Pull request by Galaxy25**
Closes #131 

Any code corrections?

### CODE REVIEW

**Comment by BrandonPacewic** [comment]
> Any code corrections?

Can you elaborate? I don't see any code changes.

**Comment by Galaxy25** [comment]
No code changes just Unity

**Review by BrandonPacewic — APPROVED** [review]
Seems good then. Let me know if I am wrong but I don't believe that any code needs to be changed.

**Comment by BrandonPacewic** [comment]
I'm getting ready to merge and updating the change log - please @me if any other changes are pushed.

**Pull request merged**
