### PR TITLE
Added copyright to files + small cleanups

### LINKED ISSUE #87: Need to add some copyright notices to `.cs` scripts
I forgot to add some copyright notices at the top of some files. I'll go through at some point at make a bulk change with another pr.

### PR DESCRIPTION
**Pull request by BrandonPacewic**
Closes #87.

### CODE REVIEW

**Comment by Galaxy25** [comment]
Is it necessary to add periods at the end of a sentence? @BrandonPacewic

**Comment by BrandonPacewic** [comment]
> Is it necessary to add periods at the end of a sentence? @BrandonPacewic

I prefer it. Most style guides say that comments should have proper grammar, this includes punctuation. It's a small thing that we don't need to enforce if you don't want to.

**Comment by Galaxy25** [comment]
Also there are a couple of errors in your code. Some of it is because the branch is behind the fixes, but also some new errors

**Comment by Galaxy25** [comment]
> > Is it necessary to add periods at the end of a sentence? @BrandonPacewic
> 
> I prefer it. Most style guides say that comments should have proper grammar, this includes punctuation. It's a small thing that we don't need to enforce if you don't want to.

I tend to program against using periods because it encourages you should be able to create multi-sentence comments instead of breaking them up and distributing it to multiple portions of the code.

**Comment by BrandonPacewic** [comment]
How would you handle this then?

https://github.com/TigardHighGDC/Augmentation/blob/10ed92d8caad502d07fe9bd8df53d0d0edee7949/Assets/Scripts/AudioManipulation.cs#L12

**Review by Galaxy25 — APPROVED** [review]

**Comment by BrandonPacewic** [comment]
Sorry about that compile error, won't every happen again 🙃

**Comment by BrandonPacewic** [comment]
I'm getting ready to merge and updating the change log - please @me if any other changes are pushed.

**Pull request merged**
