### PR TITLE
Enemy base

### PR DESCRIPTION
**Pull request by Galaxy25**
We need to have a copy of A* to continue working on the project. I'm sorry

### CODE REVIEW

**Comment by BrandonPacewic** [comment]
I'm currently working on the submodule. Please give me till the end of the block.

**Comment by Galaxy25** [comment]
Ok cool

**Comment by BrandonPacewic** [comment]
@Galaxy25 I am going to open a PR into this branch. Please delete the `AstarPathfindingProject` folder as it is going to be replaced with the git submodule. Best make a backup first as well, this could go very wrong 🙃

**Comment by BrandonPacewic** [comment]
The Submodule has been added to this branch. Please do the following things:

- Call `git pull` in the console or in GitHub desktop.
- Call `git submodule update --init --progress` in the console or the equivalent in GitHub desktop.

It also appears that you have not updated the most recent version of Unity. If that is the case please do so.

**Comment by Galaxy25** [comment]
Forgot to open it with the newest version

**Comment by Galaxy25** [comment]
Approved

**Comment by BrandonPacewic** [comment]
I'm getting ready to merge and updating the change log - please @me if any other changes are pushed.

**Review by BrandonPacewic — APPROVED** [review]

**Comment by BrandonPacewic** [comment]
Closed #33.

**Pull request merged**
