### PR TITLE
Weapon Inventory

### LINKED ISSUE #14: Weapon Inventory System
Create an inventory system that can be updated with new guns stored as a list. Give a max size to limit the amount of weapons that can be picked up and a dropping mechanic to remove old weapons. Let the player be able to change weapons by either scrolling with a mouse or using keys. I'm not sure which keys are commonly used.

### PR DESCRIPTION
**Pull request by BrandonPacewic**
Closes #14.

Still need to add the UI but works as is.

### CODE REVIEW

**Comment by Galaxy25** [comment]
@BrandonPacewic The branch isn't updated to the scene loader fix so I can't test it

**Comment by BrandonPacewic** [comment]
> @BrandonPacewic The branch isn't updated to the scene loader fix so I can't test it

@Galaxy25 Looks updated to me. What error are you getting?

**Comment by Galaxy25** [comment]
@BrandonPacewic Nevermind it was my end

**Comment by Galaxy25** [comment]
@BrandonPacewic The weapon removal seems to be working unless it's the first weapon. How hardcoded `StartingLoadout.PISTOL` since there are going to be a lot of weapon options. Also can you change your script so that weapons are dropped and able to be repickedup?

**Comment by BrandonPacewic** [comment]
> The weapon removal seems to be working unless it's the first weapon.

I'll change it so that the pistol can never be dropped for now. We can change it later.

> How hardcoded StartingLoadout.PISTOL since there are going to be a lot of weapon options.

The current starting loadouts are just a place holder as I assume that we are going to change that down the road. It will be super easy to do so.

> Also can you change your script so that weapons are dropped and able to be picked back up?

That is beyond the scope of this script. We would first need to make weapon pickups.

**Comment by Galaxy25** [comment]
> > The weapon removal seems to be working unless it's the first weapon.
> 
> I'll change it so that the pistol can never be dropped for now. We can change it later.
@BrandonPacewic I meant that the pistol cannot be dropped and instead it drops the gun after it

**Comment by Galaxy25** [comment]
@BrandonPacewic 
> > Also can you change your script so that weapons are dropped and able to be picked back up?
> 
> That is beyond the scope of this script. We would first need to make weapon pickups.
I can see how it can be separate from this script. I'll get that going once your script is good to go

**Comment by BrandonPacewic** [comment]
> > > The weapon removal seems to be working unless it's the first weapon.
> > 
> > 
> > I'll change it so that the pistol can never be dropped for now. We can change it later.
> @BrandonPacewic I meant that the pistol cannot be dropped and instead it drops the gun after it

Yea I understood that, not sure what is causing it at the moment. I would like to establish an explicit condition for what to do when you drop all weapons before I fix this. Making it so you can't drop the base weapon is my band-aid for now.

**Comment by Galaxy25** [comment]
@BrandonPacewic Also can you have an optional control of scrolling with a mouse to cycle the index?

**Comment by BrandonPacewic** [comment]
> @BrandonPacewic Also can you have an optional control of scrolling with a mouse to cycle the index?

Sure.

**Comment by Galaxy25** [comment]
@BrandonPacewic Can you change it to allow the player to drop their first weapon before I approve it?

**Review by Galaxy25 — DISMISSED** [review]

**Review by Galaxy25 — APPROVED** [review]

**Pull request merged**
