### PR TITLE
Procedural Level Map

### LINKED ISSUE #110: Create a map for traversable rooms

### LINKED ISSUE #122: Ammo doesn't update with swapping weapons
When using the inventory system the inventory doesn't update the current ammo causing weapons to have more ammo then there limit. This can be fixed by adding another list to keep track of the current ammo for each weapon

### PR DESCRIPTION
**Pull request by BrandonPacewic**
Closes #110.

This is a *massive* pr. I tried my best to separate things out into submodules where applicable and I organized my commits in a clear order for easier reviewing.

Here is a wide overview of what this pr contains:
- 17 new `.cs` files containing 1000+ lines of new code.
  - `LineConnection.cs`:
    - Contains the rendering information for the line connecting each map node.
  - `Map.cs`:
    - Contains the save information for the current map, this how the map is saved between loads.
  - `MapConfig.cs`:
    - An asset menu for configuring the map generator, this is where different difficulties should be stored.
  - `MapGenerator.cs`:
    - Largest script in this pr.
    - Is responsible for using the specified `MapConfig.cs` to generate a new `Map`.
  - `MapLayer.cs`:
    - Each `Map` is separated into different node layers, this contains the overarching information for each layer.
  - `MapManager.cs`:
    - Is responsible for loading and saving each map.
  - `MapNode.cs`:
    - Contains the information for each individual node in a layer.
    - Also responsible for changing the animations of each node depending on its state.
  - `MapPlayerTracker.cs`:
    - Responsible for moving the player across the `Map` object.
    - Also responsible for loading into a new scene once a node has been selected by the player.
  - `MapView.cs`:
    - Creates all necessary resources and objects for displaying the map UI.
  - `Node.cs`:
    - Contains all information for each `Map` node, including it's position on the background and all valid incoming and outgoing nodes.
    - Note that this script is not used by the node prefab like `MapNode.cs`, but is only internally used by the `Map.cs` script.
  - `NodeBlueprint.cs`:
    - Asset menu containing a sprite and type of each node in the map.
    - Each level should have it's own node.
  - `NodeStates.cs`:
    - Contains the `enum` for each valid state of a node; Locked, Visited, Attainable.
  - `NodeType.cs`:
    - Contains the `enum` for each type of map node; Boss, Basic Enemy, etc.
  - `Point.cs`:
    - Contains an `x` and `y` `Map` coordinate, used by all nodes to keep track of their positions.
    - Note that it is possible that Unity already has a type like this 🙃 
  - `ScrollNonUI.cs`:
    - Responsible for the ability to drag the displayed map.
  - `Extensions.cs`:
    - Contains helper functions for C# standard `List<T>`.
  - `MinMax.cs`:
    - Contains two classes used by some libraries imported.
    - I preferred to re-write them myself to avoid importing another library.
- Added 5 new submodules:
  - `Unity-Reorderable-List`:
    - Used for fancy UI when working with a `MapConfig`.
  - `DOTWeen`:
    - Animation library used for drawing node line connections and for flashing the node images.
  - `com.unity.uiextensions`:
    - Official unity UI extension needed for drawing the lines.
  - `TextMesh-Pro`:
    - Basic shader library for Unity.
    - This also includes button functionality and all the fonts you could ever want.
    - Included in both the line prefab and the node prefab.
  - `game-icons.net`
    - Collection of assets I used as placeholders until we get our own made.

Some notes about this code:
  - I do plan to expand this to include a minimap but that is not the primary purpose of this module (#142).
  - For level loading I need to make a general scene loader manager (#139).

Some things I still need to get done:
- [x] Remove all the instances of `var`.
- [x] Move the level objects into a prefab.

Make sure to run `git submodule update --init` before you open unity 🐱 

Really wanted to get this PR in before the end of sprint 6. Hope you enjoy 😸 

**Also made this a feature because this was just wayyy to much code just to call it an `enhancement` 🙃 **

### CODE REVIEW

**Comment by Galaxy25** [comment]
@BrandonPacewic I'm getting error with Github Desktop saying `fatal: not a git repository: Assets/DOTWeen/../../.git/modules/Assets/DOTWeen`

**Comment by BrandonPacewic** [comment]
> I'm getting error with Github Desktop saying `fatal: not a git repository: Assets/DOTWeen/../../.git/modules/Assets/DOTWeen`

Try cloning the repository again. I had several problems similar to this and making a clean, new clone of the repo worked for me.

**Comment by Galaxy25** [comment]
@BrandonPacewic Tried doing that it didn't work

**Comment by Galaxy25** [comment]
@BrandonPacewic It'll be easier to we just import the way Unity intends it to be stored

**Comment by BrandonPacewic** [comment]
> It'll be easier to we just import the way Unity intends it to be stored

Well it this particular section of code would just be added directly into our scripts folder. Definitely a problem with git, I'll take a look at your computer later today and see if we can figure something out. Still works fine on my computer.

**Comment by Galaxy25** [comment]
@BrandonPacewic Everything is looking great!

**Comment by Galaxy25** [comment]
@BrandonPacewic Also can these libraries be stored in packages?

**Review by Galaxy25 — APPROVED** [review]

**Review by Galaxy25 — APPROVED** [review]

**Comment by BrandonPacewic** [comment]
I'm getting ready to merge and updating the change log - please @me if any other changes are pushed.

**Pull request merged**
