### PR TITLE
NPC Text Box

### LINKED ISSUE #147: Create text box speach

### PR DESCRIPTION
**Pull request by BrandonPacewic**
Closes #147.

Open up the `Dialogue Room` scene and walk up to the bug! Enjoy 🙃

### CODE REVIEW

**Comment by Galaxy25** [comment]
@BrandonPacewic How hard would it be to change the text style when using story json? For example when two characters are speaking. Can you also add a changeable image so that it can have the speaker's face? Other than that everything is great!

**Comment by BrandonPacewic** [comment]
> @BrandonPacewic How hard would it be to change the text style when using story json? For example when two characters are speaking. Can you also add a changeable image so that it can have the speaker's face? Other than that everything is great!

You can change the style by editing the `.ink` file. It's similar to markdown (`.md`) with how it works. I'll make sure we can have more than one NPC talking at a time, and I will also add the ability to show an image for the NPC talking.

Would you also like a nametag under the picture so we can give the NPC a name?

**Comment by Galaxy25** [comment]
@BrandonPacewic Yeah that'll be great

**Comment by BrandonPacewic** [comment]
> @BrandonPacewic Yeah that'll be great

👍

**Comment by BrandonPacewic** [comment]
TODO:
- [ ] More than one NPC talking at a time
- [ ] Talking NPC image
- [ ] Talking NPC name

**Comment by BrandonPacewic** [comment]
@Galaxy25 Some major problems with merge conflicts. Please review it anyways and see if it's what you wanted. I'll fix the conflicts later.

**Comment by Galaxy25** [comment]
@BrandonPacewic Can you make a prefab for the dialogue

**Comment by BrandonPacewic** [comment]
> @BrandonPacewic Can you make a prefab for the dialogue

What are you looking to be put into a prefab? The NPC object? That will be different for each type of dialogue you want to set up because the trigger needs to have a different dialogue file in it.

**Comment by Galaxy25** [comment]
@BrandonPacewic A prefab doesn't need to have everything assigned to it

**Review by Galaxy25 — APPROVED** [review]

**Comment by BrandonPacewic** [comment]
I'm getting ready to merge and updating the change log - please @me if any other changes are pushed.

**Pull request merged**
