### PR TITLE
Audio & Bullet images added to enemies

### LINKED ISSUE #143: Add images to enemy bullets

### LINKED ISSUE #144: Add audio to enemies

### PR DESCRIPTION
**Pull request by Galaxy25**
Closes #144
Close #143

### CODE REVIEW

**Review by BrandonPacewic — DISMISSED** [review]
Looking good!

**Review by BrandonPacewic — APPROVED** [review]
Looks good to me! Any more changes?

**Comment by Galaxy25** [comment]
@BrandonPacewic No ready to merge

**Comment by BrandonPacewic** [comment]
I'm getting ready to merge and updating the change log - please @me if any other changes are pushed.

**Pull request merged**
