### PR TITLE
Weapon information

### PR DESCRIPTION
**Pull request by Galaxy25**
Added current sound for the google drive. I'm keeping it the same with the naming from the google drive for easier backtracking.

### CODE REVIEW

**Comment by BrandonPacewic** [comment]
Did you mean to reference #89?

**Comment by Galaxy25** [comment]
No

**Review by BrandonPacewic — CHANGES_REQUESTED** [review]
There are some merge conflicts that need to be addressed. Also why is there change in c# here? Looks like the same as the reload sound branch.

**Comment by Galaxy25** [comment]
@BrandonPacewic Made some changes to the WeaponData so that it can hold reload volume

**Review by BrandonPacewic — APPROVED** [review]
I'm getting ready to merge and updating the change log - please @me if any other changes are pushed.

**Pull request merged**
